name: Auto Packaging - Linux

on:
  workflow_dispatch:

jobs:
  linux-packaging:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Use Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r ./requirements/requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller
    
    - name: Build Artemis main executable
      run: |
        cd ./spec_files/Linux
        mkdir output
        mkdir output/artemis
        pyinstaller Artemis.spec
        mv -v ./dist/Artemis ./output/Artemis
        rm -rfv dist build

        pyinstaller updater.spec
        mv -v ./dist/_ArtemisUpdater ./output/_ArtemisUpdater
        rm -rfv dist build

        echo "Create single archives"
        cd output
        cp -r ../../../src/themes artemis/themes
        rm -f artemis/themes/__current_theme
        cp Artemis artemis/Artemis
        cp _ArtemisUpdater artemis/_ArtemisUpdater

        tar -czvf Artemis_linux.tar.gz Artemis -C artemis themes
        tar -czvf _ArtemisUpdater_linux.tar.gz ./_ArtemisUpdater

        echo "Create full archive for website"

        cp ../artemis3.svg artemis
        cp ../create_shortcut.sh artemis

        tar -czvf ArtemisWebDownlaod_linux.tar.gz artemis

        echo "Get size and sha256"
        python ../../__get_hash_code.py Artemis_linux.tar.gz _ArtemisUpdater_linux.tar.gz ArtemisWebDownlaod_linux.tar.gz > checksum.txt

    - uses: actions/upload-artifact@v3
      with:
        name: Artemis_Linux
        path: |
          ./spec_files/Linux/output/Artemis_linux.tar.gz
          ./spec_files/Linux/output/_ArtemisUpdater_linux.tar.gz
          ./spec_files/Linux/output/ArtemisWebDownlaod_linux.tar.gz
          ./spec_files/Linux/output/checksum.txt
