name: Nuitka - Linux 

on:
  workflow_dispatch:
    inputs:
      artemis_version:
        description: 'Version'
        required: true
        default: '4.1.0'
        type: string

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build and package
        run: sh ./building/Linux/build_linux.sh
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artemis-Linux-x86_64-${{github.event.inputs.artemis_version}}
          path: ./app.dist/
