name: PyInstaller - MacOS

on:
  workflow_dispatch:

jobs:
  macos-pyinstaller:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3

    - name: Use Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r ./requirements/requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller
    
    - name: Build Artemis main executable
      run: |
        cd ./spec_files/macOS
        pyinstaller Artemis.spec
        ls -lart

    - uses: actions/upload-artifact@v3
      with:
        name: Artemis_MacOS
        path: |
          ./spec_files/macOS/dist
